{
    let view = {
        el:'.newSong',
        template:`
        新建歌曲
        `,
        render(data){
            $(this.el).html(this.template);
        }
    }
    let model = {}
    let controller = {
        init(view,model){
            this.view=view;
            this.model=model;
            this.view.render(this.model.data)
            window.eventHub.on('upload',(data)=>{//订阅upload事件
                this.active()
                window.eventHub.emit('clickNewSong',data)
            })
            window.eventHub.on('selectSong',(data)=>{
                this.deactive()
            })
            $(this.view.el).on('click',(e)=>{
                this.active()
                window.eventHub.emit('clickNewSong')
            })
            window.eventHub.on('creat',()=>{
                this.deactive()
            })
        },
        deactive(){
            $(this.view.el).removeClass('active')
        },
        active(){
            $(this.view.el).addClass('active')
        }
    }
    controller.init(view,model)
}